### ISSUE TITLE
Compilation error: redefinition of 'char notes_chromatic [12]'

### ISSUE THREAD

**Issue by Mnikley** [connornishijima/SensoryBridge#28]
Tried to update the firmware from i think 2.X to 4.0.0, but after hitting CTRL+U i get the following exception:

```
exit status 1

Compilation error: redefinition of 'char notes_chromatic [12]'
```

- Arduino IDE 2.2.1
- newest version of FastLED and FixedPoints
- board settings as proposed in https://github.com/connornishijima/SensoryBridge/releases/tag/4.0.0
- connected board: ESP32S2 Dev Module
- 

part of the stacktrace:
```
c:\Users\usrusr\Documents\Arduino\libraries\FastLED\src/fastspi_bitbang.h:142:144: error: no matching function for call to 'delaycycles<4294967294>()'
  142 |         #define CLOCK_HI_DELAY do { delaycycles<MIN_DELAY>(); delaycycles<((SPI_SPEED > 10) ? (((SPI_SPEED-6) / 2) - MIN_DELAY) : (SPI_SPEED))>(); } while(0);
      |                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
c:\Users\usrusr\Documents\Arduino\libraries\FastLED\src/fastspi_bitbang.h:168:55: note: in expansion of macro 'CLOCK_HI_DELAY'
  168 |                         FastPin<CLOCK_PIN>::toggle(); CLOCK_HI_DELAY;
      |                                                       ^~~~~~~~~~~~~~
c:\Users\usrusr\Documents\Arduino\libraries\FastLED\src/fastled_delay.h:129:65: note: candidate: 'template<int CYCLES> void delaycycles()'
  129 | template<int CYCLES> __attribute__((always_inline)) inline void delaycycles() {
      |                                                                 ^~~~~~~~~~~
c:\Users\usrusr\Documents\Arduino\libraries\FastLED\src/fastled_delay.h:129:65: note:   template argument deduction/substitution failed:
c:\Users\usrusr\Documents\Arduino\libraries\FastLED\src/fastspi_bitbang.h:142:144: error: narrowing conversion of '4294967294' from 'long unsigned int' to 'int' [-Wnarrowing]
  142 |         #define CLOCK_HI_DELAY do { delaycycles<MIN_DELAY>(); delaycycles<((SPI_SPEED > 10) ? (((SPI_SPEED-6) / 2) - MIN_DELAY) : (SPI_SPEED))>(); } while(0);
      |                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
c:\Users\usrusr\Documents\Arduino\libraries\FastLED\src/fastspi_bitbang.h:168:55: note: in expansion of macro 'CLOCK_HI_DELAY'
  168 |                         FastPin<CLOCK_PIN>::toggle(); CLOCK_HI_DELAY;
      |                                                       ^~~~~~~~~~~~~~
```

**Comment by connornishijima** [comment]
I think I just figured this one out:

Are you on the pre-release ESP32 board definitions inside Arduino? (v3.0.0-alpha?)

Sensory Bridge Firmware was compiled using the 2.0.9 ESP32 board definitions. If you don't see 2.0.9 in your Boards Manager, you need to switch from the dev version to the stable version:

Dev versions:
https://espressif.github.io/arduino-esp32/package_esp32_dev_index.json

Stable versions:
https://espressif.github.io/arduino-esp32/package_esp32_index.json

There are breaking changes in 2.0.10 to how the I2S mic is accessed, (left and right channel data swapped positions in 2.0.10 for some reason) and ESP32 3.0.0+ is entirely incompatible because I need to port things to the entirely new I2S system in that version.

This means that any existing version of Sensory Bridge firmware as of writing this must be compiled using exactly the 2.0.9 ESP32 version in Boards Manager.

Please let me know if this fixed it!

**Comment by Mnikley** [comment]
yep, you are right, i was on v3.0.0-a because of the dev version. Switched the additional boards manager url to the stable version ([tutorial here](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)). However, after compiling/verification and the uploading this is my output:
```
In file included from c:\Users\xx\Documents\Arduino\libraries\FastLED\src/FastLED.h:75,
                 from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\SENSORY_BRIDGE_FIRMWARE.ino:74:
c:\Users\xx\Documents\Arduino\libraries\FastLED\src/fastspi.h:157:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output
 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\SENSORY_BRIDGE_FIRMWARE.ino:91:
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\i2s_audio.h:12:48: warning: 'I2S_COMM_FORMAT_I2S' is deprecated [-Wdeprecated-declarations]
   .communication_format = (i2s_comm_format_t) (I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
                                                ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\xx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.9/tools/sdk/esp32s2/include/driver/include/driver/i2s.h:16,
                 from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\i2s_audio.h:5,
                 from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\SENSORY_BRIDGE_FIRMWARE.ino:91:
C:\Users\xx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.9/tools/sdk/esp32s2/include/hal/include/hal/i2s_types.h:87:5: note: declared here
     I2S_COMM_FORMAT_I2S       __attribute__((deprecated)) = 0x01, /*!< I2S communication format I2S, correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~
In file included from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\SENSORY_BRIDGE_FIRMWARE.ino:91:
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\i2s_audio.h:12:70: warning: 'I2S_COMM_FORMAT_I2S_MSB' is deprecated [-Wdeprecated-declarations]
   .communication_format = (i2s_comm_format_t) (I2S_COMM_FORMAT_I2S | I2S_COMM_FORMAT_I2S_MSB),
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\xx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.9/tools/sdk/esp32s2/include/driver/include/driver/i2s.h:16,
                 from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\i2s_audio.h:5,
                 from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\SENSORY_BRIDGE_FIRMWARE.ino:91:
C:\Users\xx\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.9/tools/sdk/esp32s2/include/hal/include/hal/i2s_types.h:88:5: note: declared here
     I2S_COMM_FORMAT_I2S_MSB   __attribute__((deprecated)) = 0x01, /*!< I2S format MSB, (I2S_COMM_FORMAT_I2S |I2S_COMM_FORMAT_I2S_MSB) correspond to `I2S_COMM_FORMAT_STAND_I2S`*/
     ^~~~~~~~~~~~~~~~~~~~~~~
In file included from C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\SENSORY_BRIDGE_FIRMWARE.ino:98:
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h: In function 'void generate_a_weights()':
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:162:38: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   start_timing("GENERATING A-WEIGHTS");
                                      ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h: In function 'void generate_window_lookup()':
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:198:53: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   start_timing("GENERATING HANN WINDOW LOOKUP TABLE");
                                                     ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h: In function 'void init_system()':
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:291:26: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   set_mode_name(0, "GDFT");
                          ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:292:32: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   set_mode_name(1, "CHROMAGRAM");
                                ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:293:27: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   set_mode_name(2, "BLOOM");
                           ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:294:34: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   set_mode_name(3, "BLOOM (FAST)");
                                  ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:295:24: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   set_mode_name(4, "VU");
                        ^
C:\Users\xx\Desktop\SensoryBridge-4.0.0\SENSORY_BRIDGE_FIRMWARE\system.h:296:30: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   set_mode_name(5, "VU (DOT)");
                              ^
Sketch uses 825738 bytes (62%) of program storage space. Maximum is 1310720 bytes.
Global variables use 102988 bytes (31%) of dynamic memory, leaving 224692 bytes for local variables. Maximum is 327680 bytes.
esptool.py v4.5.1
Serial port COM5
Connecting...
Chip is ESP32-S2FH4 (revision v0.0)
Features: WiFi, Embedded Flash 4MB, No Embedded PSRAM, ADC and temperature sensor calibration in BLK2 of efuse V1
Crystal is 40MHz
MAC: 84:f7:03:fc:f9:9a
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 921600
Changed.
Configuring flash size...
Erasing flash (this may take a while)...
Chip erase completed successfully in 17.5s
Compressed 14656 bytes to 10171...
Writing at 0x00001000... (20 %)
Writing at 0x00001c5d... (40 %)
Writing at 0x000027ad... (60 %)
Writing at 0x000032ca... (80 %)
Writing at 0x00003c93... (100 %)
Wrote 14656 bytes (10171 compressed) at 0x00001000 in 0.3 seconds (effective 436.3 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 146...
Writing at 0x00008000... (100 %)
Wrote 3072 bytes (146 compressed) at 0x00008000 in 0.1 seconds (effective 357.3 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Writing at 0x0000e000... (100 %)
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 486.5 kbit/s)...
Hash of data verified.
Compressed 826096 bytes to 546381...
Writing at 0x00010000... (0 %)
...
Writing at 0x000d90e3... (100 %)
Wrote 826096 bytes (546381 compressed) at 0x00010000 in 10.0 seconds (effective 657.8 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
```

After which the LEDs are all white (still react to sounds though, but the pattern seems a little off). So I thought the update worked, but unfortunately the next step to update with the USB Update process doesn't work since i cannot establish a connection (Edge as browser) - console output:
```
GET https://unpkg.com/p5-webserial@0.1.1/build/p5.webserial.js net::ERR_ADDRESS_INVALID
settings.sensorybridge.rocks/:500 
        
        
        GET https://unpkg.com/@popperjs/core@2.11.5/dist/umd/popper.min.js net::ERR_ADDRESS_INVALID
settings.sensorybridge.rocks/:501 
        
        
        GET https://unpkg.com/tippy.js@6.3.7/dist/tippy-bundle.umd.min.js net::ERR_ADDRESS_INVALID
auto_serial_p5.js?version=4:2  Uncaught TypeError: p5.WebSerial is not a constructor
    at auto_serial_p5.js?version=4:2:16
(anonymous) @ auto_serial_p5.js?version=4:2
(index):488 REMOTE VERSION IS 4.0.0
auto_serial_p5.js?version=4:603  Uncaught (in promise) ReferenceError: Cannot access 'serial' before initialization
    at setup (auto_serial_p5.js?version=4:603:2)
    at v._setup (p5.min.js:2:461622)
    at v._start (p5.min.js:2:460389)
    at new v (p5.min.js:2:464548)
    at p5.min.js:2:451299
```


btw - seems like both of your links in the github README.md are dead:
- [GETTING STARTED GUIDE](https://camo.githubusercontent.com/0d0f4213dbc64f69c58852577d7c9ac5d66c4b9b6e0b4091ccd5d1875f2a5e01/68747470733a2f2f73656e736f72796272696467652e726f636b732f7475746f7269616c2f696d672f6d6173745f696e736572742e706e67)
- [GETTING STARTED](https://sensorybridge.rocks/tutorial/)
